### ISSUE TITLE
stm32 C0 Family - Missing Board 

### ISSUE THREAD

**Issue by tgrotowski** [platformio/platform-ststm32#693]
Hello,
I can't find nucleo board stm32 C031C6. https://www.st.com/en/evaluation-tools/nucleo-c031c6.html 

C0 it's quite new stm32 family with Cortex M0+ but becomes popular. There are more and more each day, it would be really useful to programming it on PlatformIO.

**Comment by minumn** [comment]
I would like to use this board as well and together with zephyr. Can anyone help me with how I could implement this?

**Comment by RudolphRiedel** [comment]
The Arduino core v2.5.0 added support for C031C6 back in end of march but the last update of the Arduino core was to v2.4.0 back in 15.5.0.
So at least for Arduino this is looking promising.

**Comment by RudolphRiedel** [comment]
I made a board definition for the nucleo-c031c6:
[nucleo_c031c6.zip](https://github.com/platformio/platform-ststm32/files/12130689/nucleo_c031c6.zip)

It kind of works but not entirely as expected or I would have opened a pull-request for this.
First of all stlink upload does not work, I set it to mbed and that works.
And then I only used it to compile an Arduino test-project which works in general but for some reason this is awfully slow, at least with SPI, I measure huge pauses between SPI.transfer(byte) calls of almost 6µs.
Is this perhaps running on Arduino-mbed instead of Arduino-core-STM32?

I am using the development version of platform-ststm32 now but that also makes no difference.

**Comment by RudolphRiedel** [comment]
I just tried this again in order to perhaps put in a pull request but now my board definition does not work anymore:
Resolving STM32C0C31 dependencies...
KeyError: Traceback (most recent call last):
  File "C:\Users\Ich\.platformio\penv\lib\site-packages\platformio\__main__.py", line 103, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "C:\Users\Ich\.platformio\penv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Ich\.platformio\penv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Ich\.platformio\penv\lib\site-packages\platformio\cli.py", line 85, in invoke
    return super().invoke(ctx)
  File "C:\Users\Ich\.platformio\penv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Ich\.platformio\penv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Ich\.platformio\penv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Ich\.platformio\penv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Ich\.platformio\penv\lib\site-packages\platformio\package\commands\list.py", line 56, in package_list_cmd
    list_project_packages(options)
  File "C:\Users\Ich\.platformio\penv\lib\site-packages\platformio\package\commands\list.py", line 179, in list_project_packages
    _found = print_project_env_platform_packages(env, options)
  File "C:\Users\Ich\.platformio\penv\lib\site-packages\platformio\package\commands\list.py", line 192, in print_project_env_platform_packages
    p = PlatformFactory.from_env(project_env)
  File "C:\Users\Ich\.platformio\penv\lib\site-packages\platformio\platform\factory.py", line 102, in from_env
    p.configure_project_packages(env, targets)
  File "C:\Users\Ich\.platformio\penv\lib\site-packages\platformio\platform\base.py", line 184, in configure_project_packages
    self.configure_default_packages(options, targets or [])
  File "C:\Users\Ich\.platformio\platforms\ststm32\platform.py", line 110, in configure_default_packages
    return PlatformBase.configure_default_packages(self, variables,
  File "C:\Users\Ich\.platformio\penv\lib\site-packages\platformio\platform\base.py", line 196, in configure_default_packages
    self.packages[_pkg_name]["optional"] = False
KeyError: 'framework-stm32cubec0'

Looks like there was a change to PlatformIO itself that removed framework-stm32cubec0???

**Comment by RudolphRiedel** [comment]
I tried this again adding my nucleo_c031c6.json to .platformio\platforms\ststm32\boards after installing 17.2.0 and I can not get this to work anymore.

It really would be nice if someone could take a look at this who has some understanding of what is going on there in regards of PlatformIO.

Overall I have to say that PlatformIO really is nice as long there already is support for the board you want to use and when the board definition supports the framework you like to use.
But beyond that PlatformIO tends to be a major pain for those like me who are unfamiliar with the inner workings of PlatformIO itself.
Do I want to know how to fix these things? Yes and No.
Yes, I am interested in fixing these things myself and therefore I would apreciate it if beeing pointed to a tutorial on how to add new boards.
But no in the sense that what I am actually trying to do is to compile software for the board I have right before me.

**Comment by ftab** [comment]
I got the same error after making a custom board definition for the STM32C0116-DK. (It works in Arduino, but I can't use Arduino due to the license)

What do we need to do to get it to recognize c0 for stm32cube?

**Comment by JikHuijberts** [comment]
This is still a problem with the current PlatformIO version. My suggestion is just like this issue https://github.com/platformio/platform-ststm32/issues/686 is adding the C0 chip range package: https://github.com/STMicroelectronics/STM32CubeC0 to the PlatformIO registry.

**Comment by jhmaloney** [comment]
I hoping to get support for a specific C0 processor, the STM32C071RB (https://www.st.com/resource/en/datasheet/stm32c071c8.pdf), which we are using in MicroBlocks to support a series of educational mictrocontroller boards ("DUELink") from GHI electronics.

Arduino has support of that processor, if that is helpful...

Thank you for considering it!

**Comment by maxgerhardt** [comment]
The OpenOCD version was recently updated in the platform, so one burden to support STM32C0 series chips was lifted.

I've updated https://github.com/maxgerhardt/pio-stm32c0 to include the STM32C071RB (generic) and the NUCLEO-C071RB board. Just select the right [project environment](https://docs.platformio.org/en/latest/integration/ide/vscode.html#project-tasks).

**Comment by maxgerhardt** [comment]
@jhmaloney are you sure a C071RB is right? The DUELink Cincobit uses a C071KB ([schematics](https://www.duelink.com/sch/gdl-mccincobit-e.pdf)), same as the [Pixobit](https://www.duelink.com/sch/gdl-mcpixobit-d.pdf).

**Comment by jhmaloney** [comment]
I'm not totally sure.

The schematic shows a C071KB. But when I compile with the Arduino IDE, I'm using the pin definitions in this file:
Library/Arduino15/packages/STMicroelectronics/hardware/stm32/2.11.0/variants/STM32C0xx/C071R(8-B)T/variant_NUCLEO_C071RB.h

I will double-check with Gus from GHI; I have Zoom call with him in a few hours.

FYI, the pin numbers in variant_NUCLEO_C071RB.h are for a Nucleo board, not for the DUELink boards, and the mapping is pretty random. It starts like this:
```
const PinName digitalPin[] = {
  PB_7,   // D0
  PB_6,   // D1
  PA_10,  // D2
  PC_7,   // D3
  PB_5,   // D4
  PB_4,   // D5
  PC_8,   // D6
  PA_8,   // D7/A6
```
so I'd be happy with a generic pin mapping such as:
```
// Digital PinName array
const PinName digitalPin[] = {
  PA_0,   // D0/A0
  PA_1,   // D1/A1
  PA_2,   // D2/A2
  PA_3,   // D3/A3
  PA_4,   // D4/A4
  PA_5,   // D5/A5
  PA_6,   // D6/A6
```
That would mean changing our existing code but it would be less confusing in the long run.

**Comment by maxgerhardt** [comment]
Well if the chip is a C071KB a C071KB pin map should be used, not that of the Nucleo C071RB one. For a generic C071KB that would be https://github.com/stm32duino/Arduino_Core_STM32/blob/main/variants/STM32C0xx/C071K(8-B)(T-U)/variant_generic.cpp and the related `.h` file. Maybe you selected the Nucleo board in the Arduino IDE because that board variant also has [the clock init code](https://github.com/stm32duino/Arduino_Core_STM32/blob/main/variants/STM32C0xx/C071R(8-B)T/variant_NUCLEO_C071RB.cpp#L111-L142)? The generic variants don't modify clock settings, so it probably runs at the 8 MHz HSI source..

In any case, I added the generic C071KB board too the aforementioned repo.

**Comment by jhmaloney** [comment]
That is a much more understandable pin map!

Clock init could be why I was using the Nucleo C071RB board; will ask Gus. If that's the case, could I just add the clock init code to the initialization code in my own code?

>  I added the generic C071KB board too the aforementioned repo

Thank you!

How I use your repo with my existing platformio installation? Would I just add a line like this to the [env] entry for the DUELink:

platform = https://github.com/maxgerhardt/pio-stm32c0.git

Many thanks for your work on this. We build MicroBlocks firmware for 50 boards in every release using PlatformIO to automate the process. However, I've been having to build the DUELink firmware using Arduino IDE then manually add it to the release file tree, which is both tedious and error prone!

**Comment by maxgerhardt** [comment]
Yes, you can add the clock init code as part of the project's `src/` code. Just create a new `.cpp` file in it, copy [the clock init](https://github.com/stm32duino/Arduino_Core_STM32/blob/main/variants/STM32C0xx/C071R(8-B)T/variant_NUCLEO_C071RB.cpp#L111-L142) code, add `#include <Arduino.h>` on top, modify it if needed, and replace `WEAK` with `extern "C"` to make the linker find the symbol with the expected name (C++ name mangling..) and as a non-weak symbol, overriding the weak symbol in `generic_clock.c`.

The `pio-stm32c0` is a PlatformIO project itself, not a `platform`. You can just download it and open it in VSCode, edit code and upload it as normal.

If you want to add C071 support to an existing PlatformIO project, you would need to 
1. copy the `boards/` folder from `pio-stm32c0` to your own project's root. This includes the critical board definition files, e.g., `genericSTM32C071KB.json`. This is what enables you to say `board = genericSTM32C071KB`.
2. copy the `ldscript_c071.ld` from `pio-stm32c0` to your own project's root. This is a special case here because they forgot to include a `ldscript.ld` STM32Duino's board variant folder for some variants..
3. Additionally copy over the `surpress_register_warnings.py` files. This suppresses some warnings that are not even showing by default in the Arduino IDE about the usage of `register`. Otherwise it spams your output.
4. Additionally copy over the `STM32C071.svd` so that during a debug session, the "Peripherals" section will be correctly decoded as that of a STM32C071 chip.
5. Create a new section in the `platformio.ini` for the board, e.g.,
```ini
[env:DUELink]
platform = ststm32@19.7.1
framework = arduino
board = genericSTM32C071KB
board_build.ldscript = ldscript_c071.ld
extra_scripts = surpress_register_warnings.py
```

Of course, if you use a upload method different that the default `stlink` one, set `upload_protocol` and `debug_tool` accordingly, e.g., `dfu` for a USB bootloader upload, et cetera.

**Comment by jhmaloney** [comment]
Wow, thank you for those detailed notes! I'll modify our existing PlatformIO installation using your instructions so everything can be built with the same automation script.

We use DFU to install firmware on the DUELink boards.

The GHI folks have created scores of DUELink boards -- over 100, I think -- that all use that exact same processor and are thus all capable of running MicroBlocks. You can run MicroBlocks on a tiny DUELink board with a single button or a few LED's.

DUELink modules can be daisy chained and controlled using a four-wire bus which means there are a *ton* of interesting modules that can be controlled by MicroBlocks.

For educators, the Cincobit and Pixobit are the most interesting starter boards. The Cincobit is very low cost; you can get 14 boards for $100. Kathy has given away a lot of those boards to educators.

Thanks for making it easier for MicroBlocks to support DUELink.

**Comment by maxgerhardt** [comment]
Great!

Just note that the need to copy over all these files is a shortcoming that should be solved in the future. Board definitions for all STM32C0 boards, alongside the SVD files, should be added to platform-ststm32 by PlatformIO staff. The missing `.ld` file should be fixed by the STM32Duino maintainers. The register warnings should be fixed by STMicroelectronics in the STM32HAL so it can flow upstream to STM32Duino. (in the past they have [refused to fix their SDK](https://github.com/stm32duino/Arduino_Core_STM32/issues/2402)). Once all that may be fixed in the future, one should be able to just write

```ini
[env:DUELink]
platform = ststm32@<some future version>
framework = arduino
board = genericSTM32C071KB
```
and have it work without any extra files.

**Comment by jhmaloney** [comment]
Does "completed" mean that after I update  I can now use the env entry posted by Max (or similar) directly without patching my Platformio installation?

**Comment by maxgerhardt** [comment]
No, the commits update the Arduino core and Zephyr and add these boards

<img width="360" height="204" alt="Image" src="https://github.com/user-attachments/assets/3c84b3b4-d368-4552-9d93-0c009ce642b8" />

So there's not a `genericSTM32C071KB` board definition yet, you still need those. The Arduino core supports far more STM32C0 chips that what was added into the ststm32 platform just now.

**Comment by valeros** [comment]
Hi @jhmaloney, is `nucleo_c071rb` a suitable replacement for that DUELink board or you need that specific STM32C071KB MCU?

**Comment by jhmaloney** [comment]
I think nucleo_c071rb is fine. I've been using that in the Arduino IDE.

**Comment by jhmaloney** [comment]
So should the env entry be something like:
```
[env:DUELink]
platform = ststm32
framework = arduino
board = nucleo_g071rb
upload_protocol = dfu
...
```

**Comment by maxgerhardt** [comment]
As of right now (since no new tag for the platform has been created yet), the best you can do is
```ini
[env:DUELink]
platform = https://github.com/platformio/platform-ststm32/archive/7c08b0c1a481983a56403e0680117d00aee7da1a.zip
framework = arduino
board = nucleo_c071rb
upload_protocol = dfu
```

**Comment by jhmaloney** [comment]
Thanks!

**Comment by jhmaloney** [comment]
I get "fatal error: stm32c0xx.h: No such file or directory"
That file was from the Arduino version of the framework. What is the equivalent file?

**Comment by maxgerhardt** [comment]
Works fine for me. Is your config correct?

<img width="1154" height="901" alt="Image" src="https://github.com/user-attachments/assets/255031d1-9917-4fe5-891e-e703afa352f1" />

**Comment by jhmaloney** [comment]
You're right, my config was wrong. Thanks!

**Comment by jhmaloney** [comment]
I can't figure out how to get it to default to using USB as the Serial device. For Arduino, I was using the build flags:
```
-D ARDUINO_USB_CDC_ON_BOOT -D USBD_USE_CDC
```
It PlatformIO it looks like I should still use "-D USBD_USE_CDC" but I what is the equivalent of ARDUINO_USB_CDC_ON_BOOT? I don't see that flag defined or used anywhere in the framework.

Symptom is that the board does not appear as a USB CDC (serial) device in the /dev folder even after power cycling it.

**Comment by maxgerhardt** [comment]
As per [docs](https://docs.platformio.org/en/latest/platforms/ststm32.html#configuration), setting
```ini
build_flags =
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
```
in the `platformio.ini` is sufficient. The [builder script](https://github.com/stm32duino/Arduino_Core_STM32/blob/main/tools/platformio/platformio-build.py#L87) will derive the rest of the needed defines.

**Comment by jhmaloney** [comment]
That did the trick! MicroBlocks is up and running on DUELink boards!

Also, thanks for the useful docs link...

One more question: is the "-D__CORTEX_SC=0" flag needed? I found that in the "boards.txt" file entry for the "NUCLEO_C071RB board". I'm guessing it is not needed in platformio...

Thank you for all your help!

**Comment by maxgerhardt** [comment]
Great to hear!

PlatformIO still gives that flag, the same way the Arduino IDE does.

https://github.com/platformio/platform-ststm32/blob/7c08b0c1a481983a56403e0680117d00aee7da1a/boards/nucleo_c071rb.json#L7-L9

However, it is likely not needed anymore. A very old version of CMSIS 4 needed this defined, otherwise it would emit a warning when doing an `#if` on an undefined macro ([reference](https://github.com/ARM-software/CMSIS_4/blob/b94b8ff1cc5aa7e054bdc4b1bf76a2069fb1fde4/CMSIS/Include/core_cmInstr.h#L221)). The new STM32Duino core 3.0.0 uses CMSIS 6 and does not need that at all. In fact, `__CORTEX_SC = 0` is the identification macro for the Secure Core SC000 ([see reference](https://arm-software.github.io/CMSIS_6/main/Core/group__version__control__gr.html#gaeaaf66c86e5ae02a0e1fe542cb7f4d8c)). But nothing uses it, so it's a dead definition. It's fine to keep it, like the Arduino core does.. Or remove it with `build_unflags = -D__CORTEX_SC=0` in the `platformio.ini`. Absolutely nothing should change. I'd just leave it alone.
